// AUTO-GENERATED by scripts/generate-registry.mjs — do not edit.
export interface RegistryEntry {
  id: string;
  name: string;
  group: "sections" | "animations";
  category: string;
  categoryLabel: string;
  file: string;
  exportName: string;
  isDefault: boolean;
  deps: string[];
  heavy: boolean;
  source: string;
}

export const registry: RegistryEntry[] = [
  {
    "id": "pro-404-404-1",
    "name": "404 1",
    "group": "sections",
    "category": "404",
    "categoryLabel": "404 页面",
    "file": "pro-404-404-1.tsx",
    "exportName": "NotFound1",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/404/404-1.tsx"
  },
  {
    "id": "pro-404-404-2",
    "name": "404 2",
    "group": "sections",
    "category": "404",
    "categoryLabel": "404 页面",
    "file": "pro-404-404-2.tsx",
    "exportName": "NotFound2",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/404/404-2.tsx"
  },
  {
    "id": "pro-404-404-3",
    "name": "404 3",
    "group": "sections",
    "category": "404",
    "categoryLabel": "404 页面",
    "file": "pro-404-404-3.tsx",
    "exportName": "NotFound3",
    "isDefault": true,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/404/404-3.tsx"
  },
  {
    "id": "pro-404-404-4",
    "name": "404 4",
    "group": "sections",
    "category": "404",
    "categoryLabel": "404 页面",
    "file": "pro-404-404-4.tsx",
    "exportName": "NotFound4",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/404/404-4.tsx"
  },
  {
    "id": "pro-404-404-5",
    "name": "404 5",
    "group": "sections",
    "category": "404",
    "categoryLabel": "404 页面",
    "file": "pro-404-404-5.tsx",
    "exportName": "NotFound5",
    "isDefault": true,
    "deps": [
      "motion",
      "matter-js",
      "lucide-react"
    ],
    "heavy": true,
    "source": "reactbits-pro/404/404-5.tsx"
  },
  {
    "id": "pro-about-about-1",
    "name": "About 1",
    "group": "sections",
    "category": "about",
    "categoryLabel": "关于",
    "file": "pro-about-about-1.tsx",
    "exportName": "About1",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/about/about-1.tsx"
  },
  {
    "id": "pro-about-about-2",
    "name": "About 2",
    "group": "sections",
    "category": "about",
    "categoryLabel": "关于",
    "file": "pro-about-about-2.tsx",
    "exportName": "About2",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/about/about-2.tsx"
  },
  {
    "id": "pro-about-about-3",
    "name": "About 3",
    "group": "sections",
    "category": "about",
    "categoryLabel": "关于",
    "file": "pro-about-about-3.tsx",
    "exportName": "About3",
    "isDefault": true,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/about/about-3.tsx"
  },
  {
    "id": "pro-about-about-4",
    "name": "About 4",
    "group": "sections",
    "category": "about",
    "categoryLabel": "关于",
    "file": "pro-about-about-4.tsx",
    "exportName": "About4",
    "isDefault": true,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/about/about-4.tsx"
  },
  {
    "id": "pro-about-about-5",
    "name": "About 5",
    "group": "sections",
    "category": "about",
    "categoryLabel": "关于",
    "file": "pro-about-about-5.tsx",
    "exportName": "About5",
    "isDefault": true,
    "deps": [
      "lenis"
    ],
    "heavy": false,
    "source": "reactbits-pro/about/about-5.tsx"
  },
  {
    "id": "pro-about-about-6",
    "name": "About 6",
    "group": "sections",
    "category": "about",
    "categoryLabel": "关于",
    "file": "pro-about-about-6.tsx",
    "exportName": "About6",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/about/about-6.tsx"
  },
  {
    "id": "pro-about-about-7",
    "name": "About 7",
    "group": "sections",
    "category": "about",
    "categoryLabel": "关于",
    "file": "pro-about-about-7.tsx",
    "exportName": "About7",
    "isDefault": true,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/about/about-7.tsx"
  },
  {
    "id": "pro-about-about-8",
    "name": "About 8",
    "group": "sections",
    "category": "about",
    "categoryLabel": "关于",
    "file": "pro-about-about-8.tsx",
    "exportName": "About8",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/about/about-8.tsx"
  },
  {
    "id": "pro-auth-auth-1",
    "name": "Auth 1",
    "group": "sections",
    "category": "auth",
    "categoryLabel": "登录注册",
    "file": "pro-auth-auth-1.tsx",
    "exportName": "Auth1",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react",
      "next-themes"
    ],
    "heavy": false,
    "source": "reactbits-pro/auth/auth-1.tsx"
  },
  {
    "id": "pro-auth-auth-2",
    "name": "Auth 2",
    "group": "sections",
    "category": "auth",
    "categoryLabel": "登录注册",
    "file": "pro-auth-auth-2.tsx",
    "exportName": "Auth2",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/auth/auth-2.tsx"
  },
  {
    "id": "pro-auth-auth-3",
    "name": "Auth 3",
    "group": "sections",
    "category": "auth",
    "categoryLabel": "登录注册",
    "file": "pro-auth-auth-3.tsx",
    "exportName": "Auth3",
    "isDefault": true,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/auth/auth-3.tsx"
  },
  {
    "id": "pro-blog-blog-1",
    "name": "Blog 1",
    "group": "sections",
    "category": "blog",
    "categoryLabel": "博客",
    "file": "pro-blog-blog-1.tsx",
    "exportName": "Blog1",
    "isDefault": false,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/blog/blog-1.tsx"
  },
  {
    "id": "pro-blog-blog-2",
    "name": "Blog 2",
    "group": "sections",
    "category": "blog",
    "categoryLabel": "博客",
    "file": "pro-blog-blog-2.tsx",
    "exportName": "Blog2",
    "isDefault": false,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/blog/blog-2.tsx"
  },
  {
    "id": "pro-blog-blog-3",
    "name": "Blog 3",
    "group": "sections",
    "category": "blog",
    "categoryLabel": "博客",
    "file": "pro-blog-blog-3.tsx",
    "exportName": "Blog3",
    "isDefault": false,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/blog/blog-3.tsx"
  },
  {
    "id": "pro-blog-blog-4",
    "name": "Blog 4",
    "group": "sections",
    "category": "blog",
    "categoryLabel": "博客",
    "file": "pro-blog-blog-4.tsx",
    "exportName": "Blog4",
    "isDefault": false,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/blog/blog-4.tsx"
  },
  {
    "id": "pro-blog-blog-5",
    "name": "Blog 5",
    "group": "sections",
    "category": "blog",
    "categoryLabel": "博客",
    "file": "pro-blog-blog-5.tsx",
    "exportName": "Blog5",
    "isDefault": false,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/blog/blog-5.tsx"
  },
  {
    "id": "pro-blog-blog-6",
    "name": "Blog 6",
    "group": "sections",
    "category": "blog",
    "categoryLabel": "博客",
    "file": "pro-blog-blog-6.tsx",
    "exportName": "Blog6",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/blog/blog-6.tsx"
  },
  {
    "id": "pro-blog-blog-7",
    "name": "Blog 7",
    "group": "sections",
    "category": "blog",
    "categoryLabel": "博客",
    "file": "pro-blog-blog-7.tsx",
    "exportName": "Blog7",
    "isDefault": true,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/blog/blog-7.tsx"
  },
  {
    "id": "pro-comparison-comparison-1",
    "name": "Comparison 1",
    "group": "sections",
    "category": "comparison",
    "categoryLabel": "对比",
    "file": "pro-comparison-comparison-1.tsx",
    "exportName": "Comparison1",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/comparison/comparison-1.tsx"
  },
  {
    "id": "pro-comparison-comparison-2",
    "name": "Comparison 2",
    "group": "sections",
    "category": "comparison",
    "categoryLabel": "对比",
    "file": "pro-comparison-comparison-2.tsx",
    "exportName": "Comparison2",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/comparison/comparison-2.tsx"
  },
  {
    "id": "pro-comparison-comparison-3",
    "name": "Comparison 3",
    "group": "sections",
    "category": "comparison",
    "categoryLabel": "对比",
    "file": "pro-comparison-comparison-3.tsx",
    "exportName": "Comparison3",
    "isDefault": true,
    "deps": [
      "lucide-react",
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/comparison/comparison-3.tsx"
  },
  {
    "id": "pro-comparison-comparison-4",
    "name": "Comparison 4",
    "group": "sections",
    "category": "comparison",
    "categoryLabel": "对比",
    "file": "pro-comparison-comparison-4.tsx",
    "exportName": "Comparison4",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/comparison/comparison-4.tsx"
  },
  {
    "id": "pro-contact-contact-1",
    "name": "Contact 1",
    "group": "sections",
    "category": "contact",
    "categoryLabel": "联系",
    "file": "pro-contact-contact-1.tsx",
    "exportName": "Contact1",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/contact/contact-1.tsx"
  },
  {
    "id": "pro-contact-contact-2",
    "name": "Contact 2",
    "group": "sections",
    "category": "contact",
    "categoryLabel": "联系",
    "file": "pro-contact-contact-2.tsx",
    "exportName": "Contact2",
    "isDefault": true,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/contact/contact-2.tsx"
  },
  {
    "id": "pro-contact-contact-3",
    "name": "Contact 3",
    "group": "sections",
    "category": "contact",
    "categoryLabel": "联系",
    "file": "pro-contact-contact-3.tsx",
    "exportName": "Contact3",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/contact/contact-3.tsx"
  },
  {
    "id": "pro-contact-contact-4",
    "name": "Contact 4",
    "group": "sections",
    "category": "contact",
    "categoryLabel": "联系",
    "file": "pro-contact-contact-4.tsx",
    "exportName": "Contact4",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/contact/contact-4.tsx"
  },
  {
    "id": "pro-contact-contact-5",
    "name": "Contact 5",
    "group": "sections",
    "category": "contact",
    "categoryLabel": "联系",
    "file": "pro-contact-contact-5.tsx",
    "exportName": "Contact5",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/contact/contact-5.tsx"
  },
  {
    "id": "pro-contact-contact-6",
    "name": "Contact 6",
    "group": "sections",
    "category": "contact",
    "categoryLabel": "联系",
    "file": "pro-contact-contact-6.tsx",
    "exportName": "Contact6",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/contact/contact-6.tsx"
  },
  {
    "id": "pro-contact-contact-7",
    "name": "Contact 7",
    "group": "sections",
    "category": "contact",
    "categoryLabel": "联系",
    "file": "pro-contact-contact-7.tsx",
    "exportName": "Contact7",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/contact/contact-7.tsx"
  },
  {
    "id": "pro-contact-contact-8",
    "name": "Contact 8",
    "group": "sections",
    "category": "contact",
    "categoryLabel": "联系",
    "file": "pro-contact-contact-8.tsx",
    "exportName": "Contact8",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/contact/contact-8.tsx"
  },
  {
    "id": "pro-cta-cta-1",
    "name": "Cta 1",
    "group": "sections",
    "category": "cta",
    "categoryLabel": "行动号召",
    "file": "pro-cta-cta-1.tsx",
    "exportName": "CTA1",
    "isDefault": true,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/cta/cta-1.tsx"
  },
  {
    "id": "pro-cta-cta-10",
    "name": "Cta 10",
    "group": "sections",
    "category": "cta",
    "categoryLabel": "行动号召",
    "file": "pro-cta-cta-10.tsx",
    "exportName": "Cta10",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/cta/cta-10.tsx"
  },
  {
    "id": "pro-cta-cta-2",
    "name": "Cta 2",
    "group": "sections",
    "category": "cta",
    "categoryLabel": "行动号召",
    "file": "pro-cta-cta-2.tsx",
    "exportName": "CTA2",
    "isDefault": true,
    "deps": [
      "gsap",
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/cta/cta-2.tsx"
  },
  {
    "id": "pro-cta-cta-3",
    "name": "Cta 3",
    "group": "sections",
    "category": "cta",
    "categoryLabel": "行动号召",
    "file": "pro-cta-cta-3.tsx",
    "exportName": "CTA3",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/cta/cta-3.tsx"
  },
  {
    "id": "pro-cta-cta-4",
    "name": "Cta 4",
    "group": "sections",
    "category": "cta",
    "categoryLabel": "行动号召",
    "file": "pro-cta-cta-4.tsx",
    "exportName": "Cta4",
    "isDefault": true,
    "deps": [
      "lucide-react",
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/cta/cta-4.tsx"
  },
  {
    "id": "pro-cta-cta-5",
    "name": "Cta 5",
    "group": "sections",
    "category": "cta",
    "categoryLabel": "行动号召",
    "file": "pro-cta-cta-5.tsx",
    "exportName": "Cta5",
    "isDefault": true,
    "deps": [
      "lucide-react",
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/cta/cta-5.tsx"
  },
  {
    "id": "pro-cta-cta-6",
    "name": "Cta 6",
    "group": "sections",
    "category": "cta",
    "categoryLabel": "行动号召",
    "file": "pro-cta-cta-6.tsx",
    "exportName": "Cta6",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/cta/cta-6.tsx"
  },
  {
    "id": "pro-cta-cta-7",
    "name": "Cta 7",
    "group": "sections",
    "category": "cta",
    "categoryLabel": "行动号召",
    "file": "pro-cta-cta-7.tsx",
    "exportName": "Cta7",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/cta/cta-7.tsx"
  },
  {
    "id": "pro-cta-cta-8",
    "name": "Cta 8",
    "group": "sections",
    "category": "cta",
    "categoryLabel": "行动号召",
    "file": "pro-cta-cta-8.tsx",
    "exportName": "Cta8",
    "isDefault": true,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/cta/cta-8.tsx"
  },
  {
    "id": "pro-cta-cta-9",
    "name": "Cta 9",
    "group": "sections",
    "category": "cta",
    "categoryLabel": "行动号召",
    "file": "pro-cta-cta-9.tsx",
    "exportName": "Cta9",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/cta/cta-9.tsx"
  },
  {
    "id": "pro-download-download-1",
    "name": "Download 1",
    "group": "sections",
    "category": "download",
    "categoryLabel": "下载",
    "file": "pro-download-download-1.tsx",
    "exportName": "Download1",
    "isDefault": false,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/download/download-1.tsx"
  },
  {
    "id": "pro-download-download-2",
    "name": "Download 2",
    "group": "sections",
    "category": "download",
    "categoryLabel": "下载",
    "file": "pro-download-download-2.tsx",
    "exportName": "Download2",
    "isDefault": false,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/download/download-2.tsx"
  },
  {
    "id": "pro-download-download-3",
    "name": "Download 3",
    "group": "sections",
    "category": "download",
    "categoryLabel": "下载",
    "file": "pro-download-download-3.tsx",
    "exportName": "Download3",
    "isDefault": false,
    "deps": [
      "motion",
      "lucide-react",
      "@react-three/fiber",
      "three"
    ],
    "heavy": true,
    "source": "reactbits-pro/download/download-3.tsx"
  },
  {
    "id": "pro-download-download-4",
    "name": "Download 4",
    "group": "sections",
    "category": "download",
    "categoryLabel": "下载",
    "file": "pro-download-download-4.tsx",
    "exportName": "Download4",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/download/download-4.tsx"
  },
  {
    "id": "pro-download-download-5",
    "name": "Download 5",
    "group": "sections",
    "category": "download",
    "categoryLabel": "下载",
    "file": "pro-download-download-5.tsx",
    "exportName": "Download5",
    "isDefault": true,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/download/download-5.tsx"
  },
  {
    "id": "pro-ecommerce-ecommerce-1",
    "name": "Ecommerce 1",
    "group": "sections",
    "category": "ecommerce",
    "categoryLabel": "电商",
    "file": "pro-ecommerce-ecommerce-1.tsx",
    "exportName": "Ecommerce1",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/ecommerce/ecommerce-1.tsx"
  },
  {
    "id": "pro-ecommerce-ecommerce-2",
    "name": "Ecommerce 2",
    "group": "sections",
    "category": "ecommerce",
    "categoryLabel": "电商",
    "file": "pro-ecommerce-ecommerce-2.tsx",
    "exportName": "Ecommerce2",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/ecommerce/ecommerce-2.tsx"
  },
  {
    "id": "pro-ecommerce-ecommerce-3",
    "name": "Ecommerce 3",
    "group": "sections",
    "category": "ecommerce",
    "categoryLabel": "电商",
    "file": "pro-ecommerce-ecommerce-3.tsx",
    "exportName": "Ecommerce3",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/ecommerce/ecommerce-3.tsx"
  },
  {
    "id": "pro-ecommerce-ecommerce-4",
    "name": "Ecommerce 4",
    "group": "sections",
    "category": "ecommerce",
    "categoryLabel": "电商",
    "file": "pro-ecommerce-ecommerce-4.tsx",
    "exportName": "Ecommerce4",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/ecommerce/ecommerce-4.tsx"
  },
  {
    "id": "pro-ecommerce-ecommerce-5",
    "name": "Ecommerce 5",
    "group": "sections",
    "category": "ecommerce",
    "categoryLabel": "电商",
    "file": "pro-ecommerce-ecommerce-5.tsx",
    "exportName": "Ecommerce5",
    "isDefault": true,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/ecommerce/ecommerce-5.tsx"
  },
  {
    "id": "pro-ecommerce-ecommerce-6",
    "name": "Ecommerce 6",
    "group": "sections",
    "category": "ecommerce",
    "categoryLabel": "电商",
    "file": "pro-ecommerce-ecommerce-6.tsx",
    "exportName": "Ecommerce6",
    "isDefault": true,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/ecommerce/ecommerce-6.tsx"
  },
  {
    "id": "pro-ecommerce-ecommerce-7",
    "name": "Ecommerce 7",
    "group": "sections",
    "category": "ecommerce",
    "categoryLabel": "电商",
    "file": "pro-ecommerce-ecommerce-7.tsx",
    "exportName": "Ecommerce7",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/ecommerce/ecommerce-7.tsx"
  },
  {
    "id": "pro-faq-faq-1",
    "name": "Faq 1",
    "group": "sections",
    "category": "faq",
    "categoryLabel": "常见问题",
    "file": "pro-faq-faq-1.tsx",
    "exportName": "FAQ1",
    "isDefault": true,
    "deps": [
      "lucide-react",
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/faq/faq-1.tsx"
  },
  {
    "id": "pro-faq-faq-2",
    "name": "Faq 2",
    "group": "sections",
    "category": "faq",
    "categoryLabel": "常见问题",
    "file": "pro-faq-faq-2.tsx",
    "exportName": "FAQ2",
    "isDefault": true,
    "deps": [
      "lucide-react",
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/faq/faq-2.tsx"
  },
  {
    "id": "pro-faq-faq-3",
    "name": "Faq 3",
    "group": "sections",
    "category": "faq",
    "categoryLabel": "常见问题",
    "file": "pro-faq-faq-3.tsx",
    "exportName": "FAQ3",
    "isDefault": true,
    "deps": [
      "lucide-react",
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/faq/faq-3.tsx"
  },
  {
    "id": "pro-faq-faq-4",
    "name": "Faq 4",
    "group": "sections",
    "category": "faq",
    "categoryLabel": "常见问题",
    "file": "pro-faq-faq-4.tsx",
    "exportName": "Faq4",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/faq/faq-4.tsx"
  },
  {
    "id": "pro-faq-faq-5",
    "name": "Faq 5",
    "group": "sections",
    "category": "faq",
    "categoryLabel": "常见问题",
    "file": "pro-faq-faq-5.tsx",
    "exportName": "Faq5",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/faq/faq-5.tsx"
  },
  {
    "id": "pro-features-features-1",
    "name": "Features 1",
    "group": "sections",
    "category": "features",
    "categoryLabel": "功能特性",
    "file": "pro-features-features-1.tsx",
    "exportName": "Features1",
    "isDefault": false,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/features/features-1.tsx"
  },
  {
    "id": "pro-features-features-2",
    "name": "Features 2",
    "group": "sections",
    "category": "features",
    "categoryLabel": "功能特性",
    "file": "pro-features-features-2.tsx",
    "exportName": "Features2",
    "isDefault": false,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/features/features-2.tsx"
  },
  {
    "id": "pro-features-features-3",
    "name": "Features 3",
    "group": "sections",
    "category": "features",
    "categoryLabel": "功能特性",
    "file": "pro-features-features-3.tsx",
    "exportName": "Features3",
    "isDefault": false,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/features/features-3.tsx"
  },
  {
    "id": "pro-features-features-4",
    "name": "Features 4",
    "group": "sections",
    "category": "features",
    "categoryLabel": "功能特性",
    "file": "pro-features-features-4.tsx",
    "exportName": "Features4",
    "isDefault": false,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/features/features-4.tsx"
  },
  {
    "id": "pro-features-features-5",
    "name": "Features 5",
    "group": "sections",
    "category": "features",
    "categoryLabel": "功能特性",
    "file": "pro-features-features-5.tsx",
    "exportName": "Features5",
    "isDefault": false,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/features/features-5.tsx"
  },
  {
    "id": "pro-features-features-6",
    "name": "Features 6",
    "group": "sections",
    "category": "features",
    "categoryLabel": "功能特性",
    "file": "pro-features-features-6.tsx",
    "exportName": "Features6",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/features/features-6.tsx"
  },
  {
    "id": "pro-features-features-7",
    "name": "Features 7",
    "group": "sections",
    "category": "features",
    "categoryLabel": "功能特性",
    "file": "pro-features-features-7.tsx",
    "exportName": "Features7",
    "isDefault": true,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/features/features-7.tsx"
  },
  {
    "id": "pro-features-features-8",
    "name": "Features 8",
    "group": "sections",
    "category": "features",
    "categoryLabel": "功能特性",
    "file": "pro-features-features-8.tsx",
    "exportName": "Features8",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/features/features-8.tsx"
  },
  {
    "id": "pro-features-features-9",
    "name": "Features 9",
    "group": "sections",
    "category": "features",
    "categoryLabel": "功能特性",
    "file": "pro-features-features-9.tsx",
    "exportName": "Features9",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/features/features-9.tsx"
  },
  {
    "id": "pro-footer-footer-1",
    "name": "Footer 1",
    "group": "sections",
    "category": "footer",
    "categoryLabel": "页脚",
    "file": "pro-footer-footer-1.tsx",
    "exportName": "Footer1",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/footer/footer-1.tsx"
  },
  {
    "id": "pro-footer-footer-2",
    "name": "Footer 2",
    "group": "sections",
    "category": "footer",
    "categoryLabel": "页脚",
    "file": "pro-footer-footer-2.tsx",
    "exportName": "Footer2",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/footer/footer-2.tsx"
  },
  {
    "id": "pro-footer-footer-3",
    "name": "Footer 3",
    "group": "sections",
    "category": "footer",
    "categoryLabel": "页脚",
    "file": "pro-footer-footer-3.tsx",
    "exportName": "Footer3",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/footer/footer-3.tsx"
  },
  {
    "id": "pro-footer-footer-4",
    "name": "Footer 4",
    "group": "sections",
    "category": "footer",
    "categoryLabel": "页脚",
    "file": "pro-footer-footer-4.tsx",
    "exportName": "Footer4",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/footer/footer-4.tsx"
  },
  {
    "id": "pro-footer-footer-5",
    "name": "Footer 5",
    "group": "sections",
    "category": "footer",
    "categoryLabel": "页脚",
    "file": "pro-footer-footer-5.tsx",
    "exportName": "Footer5",
    "isDefault": false,
    "deps": [
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/footer/footer-5.tsx"
  },
  {
    "id": "pro-footer-footer-6",
    "name": "Footer 6",
    "group": "sections",
    "category": "footer",
    "categoryLabel": "页脚",
    "file": "pro-footer-footer-6.tsx",
    "exportName": "Footer6",
    "isDefault": false,
    "deps": [
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/footer/footer-6.tsx"
  },
  {
    "id": "pro-footer-footer-7",
    "name": "Footer 7",
    "group": "sections",
    "category": "footer",
    "categoryLabel": "页脚",
    "file": "pro-footer-footer-7.tsx",
    "exportName": "Footer7",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/footer/footer-7.tsx"
  },
  {
    "id": "pro-footer-footer-8",
    "name": "Footer 8",
    "group": "sections",
    "category": "footer",
    "categoryLabel": "页脚",
    "file": "pro-footer-footer-8.tsx",
    "exportName": "Footer8",
    "isDefault": true,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/footer/footer-8.tsx"
  },
  {
    "id": "pro-hero-hero-1",
    "name": "Hero 1",
    "group": "sections",
    "category": "hero",
    "categoryLabel": "英雄区",
    "file": "pro-hero-hero-1.tsx",
    "exportName": "Hero1",
    "isDefault": false,
    "deps": [
      "lucide-react",
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/hero/hero-1.tsx"
  },
  {
    "id": "pro-hero-hero-10",
    "name": "Hero 10",
    "group": "sections",
    "category": "hero",
    "categoryLabel": "英雄区",
    "file": "pro-hero-hero-10.tsx",
    "exportName": "Hero10",
    "isDefault": false,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/hero/hero-10.tsx"
  },
  {
    "id": "pro-hero-hero-11",
    "name": "Hero 11",
    "group": "sections",
    "category": "hero",
    "categoryLabel": "英雄区",
    "file": "pro-hero-hero-11.tsx",
    "exportName": "Hero11",
    "isDefault": false,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/hero/hero-11.tsx"
  },
  {
    "id": "pro-hero-hero-12",
    "name": "Hero 12",
    "group": "sections",
    "category": "hero",
    "categoryLabel": "英雄区",
    "file": "pro-hero-hero-12.tsx",
    "exportName": "Hero12",
    "isDefault": false,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/hero/hero-12.tsx"
  },
  {
    "id": "pro-hero-hero-13",
    "name": "Hero 13",
    "group": "sections",
    "category": "hero",
    "categoryLabel": "英雄区",
    "file": "pro-hero-hero-13.tsx",
    "exportName": "Hero13",
    "isDefault": false,
    "deps": [
      "@react-three/fiber",
      "three",
      "motion",
      "lucide-react"
    ],
    "heavy": true,
    "source": "reactbits-pro/hero/hero-13.tsx"
  },
  {
    "id": "pro-hero-hero-14",
    "name": "Hero 14",
    "group": "sections",
    "category": "hero",
    "categoryLabel": "英雄区",
    "file": "pro-hero-hero-14.tsx",
    "exportName": "Hero14",
    "isDefault": false,
    "deps": [
      "lucide-react",
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/hero/hero-14.tsx"
  },
  {
    "id": "pro-hero-hero-15",
    "name": "Hero 15",
    "group": "sections",
    "category": "hero",
    "categoryLabel": "英雄区",
    "file": "pro-hero-hero-15.tsx",
    "exportName": "Hero15",
    "isDefault": false,
    "deps": [
      "lucide-react",
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/hero/hero-15.tsx"
  },
  {
    "id": "pro-hero-hero-16",
    "name": "Hero 16",
    "group": "sections",
    "category": "hero",
    "categoryLabel": "英雄区",
    "file": "pro-hero-hero-16.tsx",
    "exportName": "Hero16",
    "isDefault": false,
    "deps": [
      "lucide-react",
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/hero/hero-16.tsx"
  },
  {
    "id": "pro-hero-hero-17",
    "name": "Hero 17",
    "group": "sections",
    "category": "hero",
    "categoryLabel": "英雄区",
    "file": "pro-hero-hero-17.tsx",
    "exportName": "Hero17",
    "isDefault": false,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/hero/hero-17.tsx"
  },
  {
    "id": "pro-hero-hero-2",
    "name": "Hero 2",
    "group": "sections",
    "category": "hero",
    "categoryLabel": "英雄区",
    "file": "pro-hero-hero-2.tsx",
    "exportName": "Hero2",
    "isDefault": false,
    "deps": [
      "lucide-react",
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/hero/hero-2.tsx"
  },
  {
    "id": "pro-hero-hero-3",
    "name": "Hero 3",
    "group": "sections",
    "category": "hero",
    "categoryLabel": "英雄区",
    "file": "pro-hero-hero-3.tsx",
    "exportName": "Hero3",
    "isDefault": false,
    "deps": [
      "three",
      "lucide-react",
      "motion"
    ],
    "heavy": true,
    "source": "reactbits-pro/hero/hero-3.tsx"
  },
  {
    "id": "pro-hero-hero-4",
    "name": "Hero 4",
    "group": "sections",
    "category": "hero",
    "categoryLabel": "英雄区",
    "file": "pro-hero-hero-4.tsx",
    "exportName": "Hero4",
    "isDefault": false,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/hero/hero-4.tsx"
  },
  {
    "id": "pro-hero-hero-5",
    "name": "Hero 5",
    "group": "sections",
    "category": "hero",
    "categoryLabel": "英雄区",
    "file": "pro-hero-hero-5.tsx",
    "exportName": "Hero5",
    "isDefault": false,
    "deps": [
      "lucide-react",
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/hero/hero-5.tsx"
  },
  {
    "id": "pro-hero-hero-6",
    "name": "Hero 6",
    "group": "sections",
    "category": "hero",
    "categoryLabel": "英雄区",
    "file": "pro-hero-hero-6.tsx",
    "exportName": "Hero6",
    "isDefault": false,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/hero/hero-6.tsx"
  },
  {
    "id": "pro-hero-hero-7",
    "name": "Hero 7",
    "group": "sections",
    "category": "hero",
    "categoryLabel": "英雄区",
    "file": "pro-hero-hero-7.tsx",
    "exportName": "Hero7",
    "isDefault": false,
    "deps": [
      "@react-three/fiber",
      "@react-three/drei",
      "three",
      "motion",
      "lucide-react"
    ],
    "heavy": true,
    "source": "reactbits-pro/hero/hero-7.tsx"
  },
  {
    "id": "pro-hero-hero-8",
    "name": "Hero 8",
    "group": "sections",
    "category": "hero",
    "categoryLabel": "英雄区",
    "file": "pro-hero-hero-8.tsx",
    "exportName": "Hero8",
    "isDefault": false,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/hero/hero-8.tsx"
  },
  {
    "id": "pro-hero-hero-9",
    "name": "Hero 9",
    "group": "sections",
    "category": "hero",
    "categoryLabel": "英雄区",
    "file": "pro-hero-hero-9.tsx",
    "exportName": "Hero9",
    "isDefault": false,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/hero/hero-9.tsx"
  },
  {
    "id": "pro-how-it-works-how-it-works-1",
    "name": "How It Works 1",
    "group": "sections",
    "category": "how-it-works",
    "categoryLabel": "工作流程",
    "file": "pro-how-it-works-how-it-works-1.tsx",
    "exportName": "HowItWorks1",
    "isDefault": false,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/how-it-works/how-it-works-1.tsx"
  },
  {
    "id": "pro-how-it-works-how-it-works-2",
    "name": "How It Works 2",
    "group": "sections",
    "category": "how-it-works",
    "categoryLabel": "工作流程",
    "file": "pro-how-it-works-how-it-works-2.tsx",
    "exportName": "HowItWorks2",
    "isDefault": false,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/how-it-works/how-it-works-2.tsx"
  },
  {
    "id": "pro-how-it-works-how-it-works-3",
    "name": "How It Works 3",
    "group": "sections",
    "category": "how-it-works",
    "categoryLabel": "工作流程",
    "file": "pro-how-it-works-how-it-works-3.tsx",
    "exportName": "HowItWorks3",
    "isDefault": false,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/how-it-works/how-it-works-3.tsx"
  },
  {
    "id": "pro-how-it-works-how-it-works-4",
    "name": "How It Works 4",
    "group": "sections",
    "category": "how-it-works",
    "categoryLabel": "工作流程",
    "file": "pro-how-it-works-how-it-works-4.tsx",
    "exportName": "HowItWorks4",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/how-it-works/how-it-works-4.tsx"
  },
  {
    "id": "pro-how-it-works-how-it-works-5",
    "name": "How It Works 5",
    "group": "sections",
    "category": "how-it-works",
    "categoryLabel": "工作流程",
    "file": "pro-how-it-works-how-it-works-5.tsx",
    "exportName": "HowItWorks5",
    "isDefault": true,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/how-it-works/how-it-works-5.tsx"
  },
  {
    "id": "pro-how-it-works-how-it-works-6",
    "name": "How It Works 6",
    "group": "sections",
    "category": "how-it-works",
    "categoryLabel": "工作流程",
    "file": "pro-how-it-works-how-it-works-6.tsx",
    "exportName": "HowItWorks6",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/how-it-works/how-it-works-6.tsx"
  },
  {
    "id": "pro-navigation-navigation-1",
    "name": "Navigation 1",
    "group": "sections",
    "category": "navigation",
    "categoryLabel": "导航",
    "file": "pro-navigation-navigation-1.tsx",
    "exportName": "Navigation1",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/navigation/navigation-1.tsx"
  },
  {
    "id": "pro-navigation-navigation-10",
    "name": "Navigation 10",
    "group": "sections",
    "category": "navigation",
    "categoryLabel": "导航",
    "file": "pro-navigation-navigation-10.tsx",
    "exportName": "Navigation10",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/navigation/navigation-10.tsx"
  },
  {
    "id": "pro-navigation-navigation-11",
    "name": "Navigation 11",
    "group": "sections",
    "category": "navigation",
    "categoryLabel": "导航",
    "file": "pro-navigation-navigation-11.tsx",
    "exportName": "Navigation11",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/navigation/navigation-11.tsx"
  },
  {
    "id": "pro-navigation-navigation-2",
    "name": "Navigation 2",
    "group": "sections",
    "category": "navigation",
    "categoryLabel": "导航",
    "file": "pro-navigation-navigation-2.tsx",
    "exportName": "Navigation2",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/navigation/navigation-2.tsx"
  },
  {
    "id": "pro-navigation-navigation-3",
    "name": "Navigation 3",
    "group": "sections",
    "category": "navigation",
    "categoryLabel": "导航",
    "file": "pro-navigation-navigation-3.tsx",
    "exportName": "Navigation3",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/navigation/navigation-3.tsx"
  },
  {
    "id": "pro-navigation-navigation-4",
    "name": "Navigation 4",
    "group": "sections",
    "category": "navigation",
    "categoryLabel": "导航",
    "file": "pro-navigation-navigation-4.tsx",
    "exportName": "Navigation4",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/navigation/navigation-4.tsx"
  },
  {
    "id": "pro-navigation-navigation-5",
    "name": "Navigation 5",
    "group": "sections",
    "category": "navigation",
    "categoryLabel": "导航",
    "file": "pro-navigation-navigation-5.tsx",
    "exportName": "Navigation5",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/navigation/navigation-5.tsx"
  },
  {
    "id": "pro-navigation-navigation-6",
    "name": "Navigation 6",
    "group": "sections",
    "category": "navigation",
    "categoryLabel": "导航",
    "file": "pro-navigation-navigation-6.tsx",
    "exportName": "Navigation6",
    "isDefault": false,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/navigation/navigation-6.tsx"
  },
  {
    "id": "pro-navigation-navigation-7",
    "name": "Navigation 7",
    "group": "sections",
    "category": "navigation",
    "categoryLabel": "导航",
    "file": "pro-navigation-navigation-7.tsx",
    "exportName": "Navigation7",
    "isDefault": false,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/navigation/navigation-7.tsx"
  },
  {
    "id": "pro-navigation-navigation-8",
    "name": "Navigation 8",
    "group": "sections",
    "category": "navigation",
    "categoryLabel": "导航",
    "file": "pro-navigation-navigation-8.tsx",
    "exportName": "Navigation8",
    "isDefault": false,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/navigation/navigation-8.tsx"
  },
  {
    "id": "pro-navigation-navigation-9",
    "name": "Navigation 9",
    "group": "sections",
    "category": "navigation",
    "categoryLabel": "导航",
    "file": "pro-navigation-navigation-9.tsx",
    "exportName": "Navigation9",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/navigation/navigation-9.tsx"
  },
  {
    "id": "pro-pricing-pricing-1",
    "name": "Pricing 1",
    "group": "sections",
    "category": "pricing",
    "categoryLabel": "价格",
    "file": "pro-pricing-pricing-1.tsx",
    "exportName": "Pricing1",
    "isDefault": true,
    "deps": [
      "lucide-react",
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/pricing/pricing-1.tsx"
  },
  {
    "id": "pro-pricing-pricing-10",
    "name": "Pricing 10",
    "group": "sections",
    "category": "pricing",
    "categoryLabel": "价格",
    "file": "pro-pricing-pricing-10.tsx",
    "exportName": "Pricing10",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/pricing/pricing-10.tsx"
  },
  {
    "id": "pro-pricing-pricing-11",
    "name": "Pricing 11",
    "group": "sections",
    "category": "pricing",
    "categoryLabel": "价格",
    "file": "pro-pricing-pricing-11.tsx",
    "exportName": "Pricing11",
    "isDefault": true,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/pricing/pricing-11.tsx"
  },
  {
    "id": "pro-pricing-pricing-2",
    "name": "Pricing 2",
    "group": "sections",
    "category": "pricing",
    "categoryLabel": "价格",
    "file": "pro-pricing-pricing-2.tsx",
    "exportName": "Pricing2",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/pricing/pricing-2.tsx"
  },
  {
    "id": "pro-pricing-pricing-3",
    "name": "Pricing 3",
    "group": "sections",
    "category": "pricing",
    "categoryLabel": "价格",
    "file": "pro-pricing-pricing-3.tsx",
    "exportName": "Pricing3",
    "isDefault": true,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/pricing/pricing-3.tsx"
  },
  {
    "id": "pro-pricing-pricing-4",
    "name": "Pricing 4",
    "group": "sections",
    "category": "pricing",
    "categoryLabel": "价格",
    "file": "pro-pricing-pricing-4.tsx",
    "exportName": "Pricing4",
    "isDefault": true,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/pricing/pricing-4.tsx"
  },
  {
    "id": "pro-pricing-pricing-5",
    "name": "Pricing 5",
    "group": "sections",
    "category": "pricing",
    "categoryLabel": "价格",
    "file": "pro-pricing-pricing-5.tsx",
    "exportName": "Pricing5",
    "isDefault": false,
    "deps": [
      "lucide-react",
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/pricing/pricing-5.tsx"
  },
  {
    "id": "pro-pricing-pricing-6",
    "name": "Pricing 6",
    "group": "sections",
    "category": "pricing",
    "categoryLabel": "价格",
    "file": "pro-pricing-pricing-6.tsx",
    "exportName": "Pricing6",
    "isDefault": false,
    "deps": [
      "lucide-react",
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/pricing/pricing-6.tsx"
  },
  {
    "id": "pro-pricing-pricing-7",
    "name": "Pricing 7",
    "group": "sections",
    "category": "pricing",
    "categoryLabel": "价格",
    "file": "pro-pricing-pricing-7.tsx",
    "exportName": "Pricing7",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/pricing/pricing-7.tsx"
  },
  {
    "id": "pro-pricing-pricing-8",
    "name": "Pricing 8",
    "group": "sections",
    "category": "pricing",
    "categoryLabel": "价格",
    "file": "pro-pricing-pricing-8.tsx",
    "exportName": "Pricing8",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/pricing/pricing-8.tsx"
  },
  {
    "id": "pro-pricing-pricing-9",
    "name": "Pricing 9",
    "group": "sections",
    "category": "pricing",
    "categoryLabel": "价格",
    "file": "pro-pricing-pricing-9.tsx",
    "exportName": "Pricing9",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/pricing/pricing-9.tsx"
  },
  {
    "id": "pro-profile-profile-1",
    "name": "Profile 1",
    "group": "sections",
    "category": "profile",
    "categoryLabel": "个人资料",
    "file": "pro-profile-profile-1.tsx",
    "exportName": "Profile1",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/profile/profile-1.tsx"
  },
  {
    "id": "pro-profile-profile-2",
    "name": "Profile 2",
    "group": "sections",
    "category": "profile",
    "categoryLabel": "个人资料",
    "file": "pro-profile-profile-2.tsx",
    "exportName": "Profile2",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/profile/profile-2.tsx"
  },
  {
    "id": "pro-profile-profile-3",
    "name": "Profile 3",
    "group": "sections",
    "category": "profile",
    "categoryLabel": "个人资料",
    "file": "pro-profile-profile-3.tsx",
    "exportName": "Profile3",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/profile/profile-3.tsx"
  },
  {
    "id": "pro-showcase-showcase-1",
    "name": "Showcase 1",
    "group": "sections",
    "category": "showcase",
    "categoryLabel": "案例展示",
    "file": "pro-showcase-showcase-1.tsx",
    "exportName": "Showcase1",
    "isDefault": false,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/showcase/showcase-1.tsx"
  },
  {
    "id": "pro-showcase-showcase-2",
    "name": "Showcase 2",
    "group": "sections",
    "category": "showcase",
    "categoryLabel": "案例展示",
    "file": "pro-showcase-showcase-2.tsx",
    "exportName": "Showcase2",
    "isDefault": false,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/showcase/showcase-2.tsx"
  },
  {
    "id": "pro-showcase-showcase-3",
    "name": "Showcase 3",
    "group": "sections",
    "category": "showcase",
    "categoryLabel": "案例展示",
    "file": "pro-showcase-showcase-3.tsx",
    "exportName": "Showcase3",
    "isDefault": false,
    "deps": [
      "@react-three/fiber",
      "@react-three/drei",
      "three",
      "motion"
    ],
    "heavy": true,
    "source": "reactbits-pro/showcase/showcase-3.tsx"
  },
  {
    "id": "pro-showcase-showcase-4",
    "name": "Showcase 4",
    "group": "sections",
    "category": "showcase",
    "categoryLabel": "案例展示",
    "file": "pro-showcase-showcase-4.tsx",
    "exportName": "Showcase4",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/showcase/showcase-4.tsx"
  },
  {
    "id": "pro-showcase-showcase-5",
    "name": "Showcase 5",
    "group": "sections",
    "category": "showcase",
    "categoryLabel": "案例展示",
    "file": "pro-showcase-showcase-5.tsx",
    "exportName": "Showcase5",
    "isDefault": true,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/showcase/showcase-5.tsx"
  },
  {
    "id": "pro-social-proof-social-proof-1",
    "name": "Social Proof 1",
    "group": "sections",
    "category": "social-proof",
    "categoryLabel": "社会证明",
    "file": "pro-social-proof-social-proof-1.tsx",
    "exportName": "SocialProof1",
    "isDefault": true,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/social-proof/social-proof-1.tsx"
  },
  {
    "id": "pro-social-proof-social-proof-10",
    "name": "Social Proof 10",
    "group": "sections",
    "category": "social-proof",
    "categoryLabel": "社会证明",
    "file": "pro-social-proof-social-proof-10.tsx",
    "exportName": "SocialProof10",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/social-proof/social-proof-10.tsx"
  },
  {
    "id": "pro-social-proof-social-proof-11",
    "name": "Social Proof 11",
    "group": "sections",
    "category": "social-proof",
    "categoryLabel": "社会证明",
    "file": "pro-social-proof-social-proof-11.tsx",
    "exportName": "SocialProof11",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/social-proof/social-proof-11.tsx"
  },
  {
    "id": "pro-social-proof-social-proof-12",
    "name": "Social Proof 12",
    "group": "sections",
    "category": "social-proof",
    "categoryLabel": "社会证明",
    "file": "pro-social-proof-social-proof-12.tsx",
    "exportName": "SocialProof12",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/social-proof/social-proof-12.tsx"
  },
  {
    "id": "pro-social-proof-social-proof-2",
    "name": "Social Proof 2",
    "group": "sections",
    "category": "social-proof",
    "categoryLabel": "社会证明",
    "file": "pro-social-proof-social-proof-2.tsx",
    "exportName": "SocialProof2",
    "isDefault": true,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/social-proof/social-proof-2.tsx"
  },
  {
    "id": "pro-social-proof-social-proof-3",
    "name": "Social Proof 3",
    "group": "sections",
    "category": "social-proof",
    "categoryLabel": "社会证明",
    "file": "pro-social-proof-social-proof-3.tsx",
    "exportName": "SocialProof3",
    "isDefault": true,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/social-proof/social-proof-3.tsx"
  },
  {
    "id": "pro-social-proof-social-proof-4",
    "name": "Social Proof 4",
    "group": "sections",
    "category": "social-proof",
    "categoryLabel": "社会证明",
    "file": "pro-social-proof-social-proof-4.tsx",
    "exportName": "SocialProof4",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/social-proof/social-proof-4.tsx"
  },
  {
    "id": "pro-social-proof-social-proof-5",
    "name": "Social Proof 5",
    "group": "sections",
    "category": "social-proof",
    "categoryLabel": "社会证明",
    "file": "pro-social-proof-social-proof-5.tsx",
    "exportName": "SocialProof5",
    "isDefault": true,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/social-proof/social-proof-5.tsx"
  },
  {
    "id": "pro-social-proof-social-proof-6",
    "name": "Social Proof 6",
    "group": "sections",
    "category": "social-proof",
    "categoryLabel": "社会证明",
    "file": "pro-social-proof-social-proof-6.tsx",
    "exportName": "SocialProof6",
    "isDefault": true,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/social-proof/social-proof-6.tsx"
  },
  {
    "id": "pro-social-proof-social-proof-7",
    "name": "Social Proof 7",
    "group": "sections",
    "category": "social-proof",
    "categoryLabel": "社会证明",
    "file": "pro-social-proof-social-proof-7.tsx",
    "exportName": "SocialProof7",
    "isDefault": false,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/social-proof/social-proof-7.tsx"
  },
  {
    "id": "pro-social-proof-social-proof-8",
    "name": "Social Proof 8",
    "group": "sections",
    "category": "social-proof",
    "categoryLabel": "社会证明",
    "file": "pro-social-proof-social-proof-8.tsx",
    "exportName": "SocialProof8",
    "isDefault": false,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/social-proof/social-proof-8.tsx"
  },
  {
    "id": "pro-social-proof-social-proof-9",
    "name": "Social Proof 9",
    "group": "sections",
    "category": "social-proof",
    "categoryLabel": "社会证明",
    "file": "pro-social-proof-social-proof-9.tsx",
    "exportName": "SocialProof9",
    "isDefault": false,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/social-proof/social-proof-9.tsx"
  },
  {
    "id": "pro-stats-stats-1",
    "name": "Stats 1",
    "group": "sections",
    "category": "stats",
    "categoryLabel": "数据统计",
    "file": "pro-stats-stats-1.tsx",
    "exportName": "Stats1",
    "isDefault": true,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/stats/stats-1.tsx"
  },
  {
    "id": "pro-stats-stats-10",
    "name": "Stats 10",
    "group": "sections",
    "category": "stats",
    "categoryLabel": "数据统计",
    "file": "pro-stats-stats-10.tsx",
    "exportName": "Stats10",
    "isDefault": true,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/stats/stats-10.tsx"
  },
  {
    "id": "pro-stats-stats-11",
    "name": "Stats 11",
    "group": "sections",
    "category": "stats",
    "categoryLabel": "数据统计",
    "file": "pro-stats-stats-11.tsx",
    "exportName": "Stats11",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/stats/stats-11.tsx"
  },
  {
    "id": "pro-stats-stats-2",
    "name": "Stats 2",
    "group": "sections",
    "category": "stats",
    "categoryLabel": "数据统计",
    "file": "pro-stats-stats-2.tsx",
    "exportName": "Stats2",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/stats/stats-2.tsx"
  },
  {
    "id": "pro-stats-stats-3",
    "name": "Stats 3",
    "group": "sections",
    "category": "stats",
    "categoryLabel": "数据统计",
    "file": "pro-stats-stats-3.tsx",
    "exportName": "Stats3",
    "isDefault": true,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/stats/stats-3.tsx"
  },
  {
    "id": "pro-stats-stats-4",
    "name": "Stats 4",
    "group": "sections",
    "category": "stats",
    "categoryLabel": "数据统计",
    "file": "pro-stats-stats-4.tsx",
    "exportName": "Stats4",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/stats/stats-4.tsx"
  },
  {
    "id": "pro-stats-stats-5",
    "name": "Stats 5",
    "group": "sections",
    "category": "stats",
    "categoryLabel": "数据统计",
    "file": "pro-stats-stats-5.tsx",
    "exportName": "Stats5",
    "isDefault": true,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/stats/stats-5.tsx"
  },
  {
    "id": "pro-stats-stats-6",
    "name": "Stats 6",
    "group": "sections",
    "category": "stats",
    "categoryLabel": "数据统计",
    "file": "pro-stats-stats-6.tsx",
    "exportName": "Stats6",
    "isDefault": true,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/stats/stats-6.tsx"
  },
  {
    "id": "pro-stats-stats-7",
    "name": "Stats 7",
    "group": "sections",
    "category": "stats",
    "categoryLabel": "数据统计",
    "file": "pro-stats-stats-7.tsx",
    "exportName": "Stats7",
    "isDefault": true,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/stats/stats-7.tsx"
  },
  {
    "id": "pro-stats-stats-8",
    "name": "Stats 8",
    "group": "sections",
    "category": "stats",
    "categoryLabel": "数据统计",
    "file": "pro-stats-stats-8.tsx",
    "exportName": "Stats8",
    "isDefault": true,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/stats/stats-8.tsx"
  },
  {
    "id": "pro-stats-stats-9",
    "name": "Stats 9",
    "group": "sections",
    "category": "stats",
    "categoryLabel": "数据统计",
    "file": "pro-stats-stats-9.tsx",
    "exportName": "Stats9",
    "isDefault": true,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/stats/stats-9.tsx"
  },
  {
    "id": "pro-waitlist-waitlist-1",
    "name": "Waitlist 1",
    "group": "sections",
    "category": "waitlist",
    "categoryLabel": "等候名单",
    "file": "pro-waitlist-waitlist-1.tsx",
    "exportName": "Waitlist1",
    "isDefault": true,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/waitlist/waitlist-1.tsx"
  },
  {
    "id": "pro-waitlist-waitlist-2",
    "name": "Waitlist 2",
    "group": "sections",
    "category": "waitlist",
    "categoryLabel": "等候名单",
    "file": "pro-waitlist-waitlist-2.tsx",
    "exportName": "Waitlist2",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-pro/waitlist/waitlist-2.tsx"
  },
  {
    "id": "pro-waitlist-waitlist-3",
    "name": "Waitlist 3",
    "group": "sections",
    "category": "waitlist",
    "categoryLabel": "等候名单",
    "file": "pro-waitlist-waitlist-3.tsx",
    "exportName": "Waitlist3",
    "isDefault": true,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-pro/waitlist/waitlist-3.tsx"
  },
  {
    "id": "anim-3d-letter-swap",
    "name": "3d Letter Swap",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-3d-letter-swap.tsx",
    "exportName": "ThreeDLetterSwap",
    "isDefault": true,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-starter/tw/3d-letter-swap.tsx"
  },
  {
    "id": "anim-3d-text-reveal",
    "name": "3d Text Reveal",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-3d-text-reveal.tsx",
    "exportName": "ThreeDTextReveal",
    "isDefault": true,
    "deps": [
      "gsap",
      "@gsap/react"
    ],
    "heavy": false,
    "source": "reactbits-starter/tw/3d-text-reveal.tsx"
  },
  {
    "id": "anim-agentic-ball",
    "name": "Agentic Ball",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-agentic-ball.tsx",
    "exportName": "AgenticBall",
    "isDefault": true,
    "deps": [
      "@react-three/fiber",
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/agentic-ball.tsx"
  },
  {
    "id": "anim-ai-blob",
    "name": "Ai Blob",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-ai-blob.tsx",
    "exportName": "AIBlob",
    "isDefault": true,
    "deps": [
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/ai-blob.tsx"
  },
  {
    "id": "anim-animated-list",
    "name": "Animated List",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-animated-list.tsx",
    "exportName": "AnimatedList",
    "isDefault": true,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-starter/tw/animated-list.tsx"
  },
  {
    "id": "anim-ascii-cursor",
    "name": "Ascii Cursor",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-ascii-cursor.tsx",
    "exportName": "AsciiCursor",
    "isDefault": true,
    "deps": [
      "@react-three/fiber",
      "@react-three/drei",
      "@react-three/postprocessing",
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/ascii-cursor.tsx"
  },
  {
    "id": "anim-ascii-tiles",
    "name": "Ascii Tiles",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-ascii-tiles.tsx",
    "exportName": "AsciiTiles",
    "isDefault": true,
    "deps": [
      "@react-three/fiber",
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/ascii-tiles.tsx"
  },
  {
    "id": "anim-ascii-waves",
    "name": "Ascii Waves",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-ascii-waves.tsx",
    "exportName": "AsciiWaves",
    "isDefault": true,
    "deps": [
      "@react-three/fiber",
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/ascii-waves.tsx"
  },
  {
    "id": "anim-aurora-blur",
    "name": "Aurora Blur",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-aurora-blur.tsx",
    "exportName": "AuroraBlur",
    "isDefault": true,
    "deps": [
      "@react-three/fiber",
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/aurora-blur.tsx"
  },
  {
    "id": "anim-black-hole",
    "name": "Black Hole",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-black-hole.tsx",
    "exportName": "BlackHole",
    "isDefault": true,
    "deps": [
      "@react-three/fiber",
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/black-hole.tsx"
  },
  {
    "id": "anim-blinking-squares",
    "name": "Blinking Squares",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-blinking-squares.tsx",
    "exportName": "BlinkingSquares",
    "isDefault": true,
    "deps": [
      "@react-three/fiber",
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/blinking-squares.tsx"
  },
  {
    "id": "anim-blur-highlight",
    "name": "Blur Highlight",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-blur-highlight.tsx",
    "exportName": "BlurHighlight",
    "isDefault": true,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-starter/tw/blur-highlight.tsx"
  },
  {
    "id": "anim-blurred-rays",
    "name": "Blurred Rays",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-blurred-rays.tsx",
    "exportName": "BlurredRays",
    "isDefault": true,
    "deps": [
      "@react-three/fiber",
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/blurred-rays.tsx"
  },
  {
    "id": "anim-center-flow",
    "name": "Center Flow",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-center-flow.tsx",
    "exportName": "CenterFlow",
    "isDefault": true,
    "deps": [
      "next-themes"
    ],
    "heavy": false,
    "source": "reactbits-starter/tw/center-flow.tsx"
  },
  {
    "id": "anim-chroma-blinds",
    "name": "Chroma Blinds",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-chroma-blinds.tsx",
    "exportName": "ChromaBlinds",
    "isDefault": true,
    "deps": [
      "@react-three/fiber",
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/chroma-blinds.tsx"
  },
  {
    "id": "anim-chroma-card",
    "name": "Chroma Card",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-chroma-card.tsx",
    "exportName": "ChromaCard",
    "isDefault": true,
    "deps": [
      "@react-three/fiber",
      "three",
      "gsap"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/chroma-card.tsx"
  },
  {
    "id": "anim-chroma-waves",
    "name": "Chroma Waves",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-chroma-waves.tsx",
    "exportName": "ChromaWaves",
    "isDefault": true,
    "deps": [
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/chroma-waves.tsx"
  },
  {
    "id": "anim-circle-gallery",
    "name": "Circle Gallery",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-circle-gallery.tsx",
    "exportName": "CircleGallery",
    "isDefault": true,
    "deps": [
      "gsap"
    ],
    "heavy": false,
    "source": "reactbits-starter/tw/circle-gallery.tsx"
  },
  {
    "id": "anim-circle-stack",
    "name": "Circle Stack",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-circle-stack.tsx",
    "exportName": "CircleStack",
    "isDefault": true,
    "deps": [],
    "heavy": false,
    "source": "reactbits-starter/tw/circle-stack.tsx"
  },
  {
    "id": "anim-circles",
    "name": "Circles",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-circles.tsx",
    "exportName": "Circles",
    "isDefault": true,
    "deps": [],
    "heavy": false,
    "source": "reactbits-starter/tw/circles.tsx"
  },
  {
    "id": "anim-click-stack",
    "name": "Click Stack",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-click-stack.tsx",
    "exportName": "ClickStack",
    "isDefault": true,
    "deps": [
      "gsap"
    ],
    "heavy": false,
    "source": "reactbits-starter/tw/click-stack.tsx"
  },
  {
    "id": "anim-color-loops",
    "name": "Color Loops",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-color-loops.tsx",
    "exportName": "ColorLoops",
    "isDefault": true,
    "deps": [
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/color-loops.tsx"
  },
  {
    "id": "anim-comparison-slider",
    "name": "Comparison Slider",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-comparison-slider.tsx",
    "exportName": "ComparisonSlider",
    "isDefault": true,
    "deps": [
      "gsap",
      "@gsap/react",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-starter/tw/comparison-slider.tsx"
  },
  {
    "id": "anim-credit-card",
    "name": "Credit Card",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-credit-card.tsx",
    "exportName": "CreditCard",
    "isDefault": true,
    "deps": [
      "lucide-react",
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-starter/tw/credit-card.tsx"
  },
  {
    "id": "anim-cursor-wave",
    "name": "Cursor Wave",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-cursor-wave.tsx",
    "exportName": "CursorWave",
    "isDefault": true,
    "deps": [],
    "heavy": false,
    "source": "reactbits-starter/tw/cursor-wave.tsx"
  },
  {
    "id": "anim-custom-cursor",
    "name": "Custom Cursor",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-custom-cursor.tsx",
    "exportName": "CustomCursor",
    "isDefault": true,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-starter/tw/custom-cursor.tsx"
  },
  {
    "id": "anim-depth-card",
    "name": "Depth Card",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-depth-card.tsx",
    "exportName": "DepthCard",
    "isDefault": true,
    "deps": [],
    "heavy": false,
    "source": "reactbits-starter/tw/depth-card.tsx"
  },
  {
    "id": "anim-device",
    "name": "Device",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-device.tsx",
    "exportName": "Device",
    "isDefault": true,
    "deps": [
      "motion",
      "lenis"
    ],
    "heavy": false,
    "source": "reactbits-starter/tw/device.tsx"
  },
  {
    "id": "anim-dither-cursor",
    "name": "Dither Cursor",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-dither-cursor.tsx",
    "exportName": "DitherCursor",
    "isDefault": true,
    "deps": [
      "@react-three/fiber",
      "@react-three/drei",
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/dither-cursor.tsx"
  },
  {
    "id": "anim-dither-wave",
    "name": "Dither Wave",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-dither-wave.tsx",
    "exportName": "DitherWave",
    "isDefault": true,
    "deps": [
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/dither-wave.tsx"
  },
  {
    "id": "anim-dot-shift",
    "name": "Dot Shift",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-dot-shift.tsx",
    "exportName": "DotShift",
    "isDefault": true,
    "deps": [
      "@react-three/fiber",
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/dot-shift.tsx"
  },
  {
    "id": "anim-draggable-grid",
    "name": "Draggable Grid",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-draggable-grid.tsx",
    "exportName": "DraggableGrid",
    "isDefault": true,
    "deps": [
      "gsap",
      "@gsap/react"
    ],
    "heavy": false,
    "source": "reactbits-starter/tw/draggable-grid.tsx"
  },
  {
    "id": "anim-falling-rays",
    "name": "Falling Rays",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-falling-rays.tsx",
    "exportName": "FallingRays",
    "isDefault": true,
    "deps": [
      "@react-three/fiber",
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/falling-rays.tsx"
  },
  {
    "id": "anim-flame-paths",
    "name": "Flame Paths",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-flame-paths.tsx",
    "exportName": "FlamePaths",
    "isDefault": true,
    "deps": [
      "@react-three/fiber",
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/flame-paths.tsx"
  },
  {
    "id": "anim-flicker",
    "name": "Flicker",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-flicker.tsx",
    "exportName": "Flicker",
    "isDefault": true,
    "deps": [],
    "heavy": false,
    "source": "reactbits-starter/tw/flicker.tsx"
  },
  {
    "id": "anim-fog-sphere",
    "name": "Fog Sphere",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-fog-sphere.tsx",
    "exportName": "FogSphere",
    "isDefault": true,
    "deps": [
      "@react-three/fiber",
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/fog-sphere.tsx"
  },
  {
    "id": "anim-frame-border",
    "name": "Frame Border",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-frame-border.tsx",
    "exportName": "FrameBorder",
    "isDefault": true,
    "deps": [
      "@react-three/fiber",
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/frame-border.tsx"
  },
  {
    "id": "anim-glass-cursor",
    "name": "Glass Cursor",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-glass-cursor.tsx",
    "exportName": "GlassCursor",
    "isDefault": true,
    "deps": [
      "@react-three/fiber",
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/glass-cursor.tsx"
  },
  {
    "id": "anim-glass-flow",
    "name": "Glass Flow",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-glass-flow.tsx",
    "exportName": "GlassFlow",
    "isDefault": true,
    "deps": [
      "@react-three/fiber",
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/glass-flow.tsx"
  },
  {
    "id": "anim-glass-tiles",
    "name": "Glass Tiles",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-glass-tiles.tsx",
    "exportName": "GlassTiles",
    "isDefault": true,
    "deps": [
      "@react-three/fiber",
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/glass-tiles.tsx"
  },
  {
    "id": "anim-glitch-text",
    "name": "Glitch Text",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-glitch-text.tsx",
    "exportName": "GlitchText",
    "isDefault": true,
    "deps": [],
    "heavy": false,
    "source": "reactbits-starter/tw/glitch-text.tsx"
  },
  {
    "id": "anim-glitter-warp",
    "name": "Glitter Warp",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-glitter-warp.tsx",
    "exportName": "GlitterWarp",
    "isDefault": true,
    "deps": [
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/glitter-warp.tsx"
  },
  {
    "id": "anim-globe",
    "name": "Globe",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-globe.tsx",
    "exportName": "Globe",
    "isDefault": true,
    "deps": [],
    "heavy": false,
    "source": "reactbits-starter/tw/globe.tsx"
  },
  {
    "id": "anim-gradient-bars",
    "name": "Gradient Bars",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-gradient-bars.tsx",
    "exportName": "GradientBars",
    "isDefault": true,
    "deps": [
      "@react-three/fiber",
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/gradient-bars.tsx"
  },
  {
    "id": "anim-gradient-blob",
    "name": "Gradient Blob",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-gradient-blob.tsx",
    "exportName": "GradientBlob",
    "isDefault": true,
    "deps": [
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/gradient-blob.tsx"
  },
  {
    "id": "anim-gradient-carousel",
    "name": "Gradient Carousel",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-gradient-carousel.tsx",
    "exportName": "GradientCarousel",
    "isDefault": true,
    "deps": [
      "gsap"
    ],
    "heavy": false,
    "source": "reactbits-starter/tw/gradient-carousel.tsx"
  },
  {
    "id": "anim-grain-wave",
    "name": "Grain Wave",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-grain-wave.tsx",
    "exportName": "GrainWave",
    "isDefault": true,
    "deps": [
      "@react-three/fiber",
      "three",
      "next-themes"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/grain-wave.tsx"
  },
  {
    "id": "anim-halftone-vortex",
    "name": "Halftone Vortex",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-halftone-vortex.tsx",
    "exportName": "HalftoneVortex",
    "isDefault": true,
    "deps": [
      "@react-three/fiber",
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/halftone-vortex.tsx"
  },
  {
    "id": "anim-halftone-wave",
    "name": "Halftone Wave",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-halftone-wave.tsx",
    "exportName": "HalftoneWave",
    "isDefault": true,
    "deps": [
      "@react-three/fiber",
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/halftone-wave.tsx"
  },
  {
    "id": "anim-hover-preview",
    "name": "Hover Preview",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-hover-preview.tsx",
    "exportName": "HoverPreview",
    "isDefault": true,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-starter/tw/hover-preview.tsx"
  },
  {
    "id": "anim-infinite-gallery",
    "name": "Infinite Gallery",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-infinite-gallery.tsx",
    "exportName": "InfiniteGallery",
    "isDefault": true,
    "deps": [
      "@react-three/fiber",
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/infinite-gallery.tsx"
  },
  {
    "id": "anim-light-droplets",
    "name": "Light Droplets",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-light-droplets.tsx",
    "exportName": "LightDroplets",
    "isDefault": true,
    "deps": [
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/light-droplets.tsx"
  },
  {
    "id": "anim-lightspeed",
    "name": "Lightspeed",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-lightspeed.tsx",
    "exportName": "Lightspeed",
    "isDefault": true,
    "deps": [
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/lightspeed.tsx"
  },
  {
    "id": "anim-liquid-ascii",
    "name": "Liquid Ascii",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-liquid-ascii.tsx",
    "exportName": "LiquidAscii",
    "isDefault": true,
    "deps": [],
    "heavy": false,
    "source": "reactbits-starter/tw/liquid-ascii.tsx"
  },
  {
    "id": "anim-liquid-bars",
    "name": "Liquid Bars",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-liquid-bars.tsx",
    "exportName": "LiquidBars",
    "isDefault": true,
    "deps": [
      "@react-three/fiber",
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/liquid-bars.tsx"
  },
  {
    "id": "anim-liquid-lines",
    "name": "Liquid Lines",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-liquid-lines.tsx",
    "exportName": "LiquidLines",
    "isDefault": true,
    "deps": [
      "@react-three/fiber",
      "three",
      "next-themes"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/liquid-lines.tsx"
  },
  {
    "id": "anim-liquid-swap",
    "name": "Liquid Swap",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-liquid-swap.tsx",
    "exportName": "LiquidSwap",
    "isDefault": true,
    "deps": [
      "three",
      "gsap"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/liquid-swap.tsx"
  },
  {
    "id": "anim-magic-transform",
    "name": "Magic Transform",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-magic-transform.tsx",
    "exportName": "MagicTransform",
    "isDefault": true,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-starter/tw/magic-transform.tsx"
  },
  {
    "id": "anim-metallic-swirl",
    "name": "Metallic Swirl",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-metallic-swirl.tsx",
    "exportName": "MetallicSwirl",
    "isDefault": true,
    "deps": [
      "@react-three/fiber",
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/metallic-swirl.tsx"
  },
  {
    "id": "anim-modal-cards",
    "name": "Modal Cards",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-modal-cards.tsx",
    "exportName": "ModalCards",
    "isDefault": true,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-starter/tw/modal-cards.tsx"
  },
  {
    "id": "anim-mosaic",
    "name": "Mosaic",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-mosaic.tsx",
    "exportName": "Mosaic",
    "isDefault": true,
    "deps": [
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/mosaic.tsx"
  },
  {
    "id": "anim-neon-reveal",
    "name": "Neon Reveal",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-neon-reveal.tsx",
    "exportName": "NeonReveal",
    "isDefault": true,
    "deps": [
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/neon-reveal.tsx"
  },
  {
    "id": "anim-parallax-cards",
    "name": "Parallax Cards",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-parallax-cards.tsx",
    "exportName": "ParallaxCards",
    "isDefault": true,
    "deps": [
      "gsap"
    ],
    "heavy": false,
    "source": "reactbits-starter/tw/parallax-cards.tsx"
  },
  {
    "id": "anim-parallax-carousel",
    "name": "Parallax Carousel",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-parallax-carousel.tsx",
    "exportName": "ParallaxCarousel",
    "isDefault": true,
    "deps": [
      "@react-three/fiber",
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/parallax-carousel.tsx"
  },
  {
    "id": "anim-parallax-pills",
    "name": "Parallax Pills",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-parallax-pills.tsx",
    "exportName": "ParallaxPills",
    "isDefault": true,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-starter/tw/parallax-pills.tsx"
  },
  {
    "id": "anim-particle-text",
    "name": "Particle Text",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-particle-text.tsx",
    "exportName": "ParticleText",
    "isDefault": true,
    "deps": [],
    "heavy": false,
    "source": "reactbits-starter/tw/particle-text.tsx"
  },
  {
    "id": "anim-perspective-grid",
    "name": "Perspective Grid",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-perspective-grid.tsx",
    "exportName": "PerspectiveGrid",
    "isDefault": true,
    "deps": [
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/perspective-grid.tsx"
  },
  {
    "id": "anim-pixel-reveal",
    "name": "Pixel Reveal",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-pixel-reveal.tsx",
    "exportName": "PixelReveal",
    "isDefault": true,
    "deps": [
      "@react-three/fiber",
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/pixel-reveal.tsx"
  },
  {
    "id": "anim-pixelate-hover",
    "name": "Pixelate Hover",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-pixelate-hover.tsx",
    "exportName": "PixelateHover",
    "isDefault": true,
    "deps": [
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/pixelate-hover.tsx"
  },
  {
    "id": "anim-portal",
    "name": "Portal",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-portal.tsx",
    "exportName": "Portal",
    "isDefault": true,
    "deps": [
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/portal.tsx"
  },
  {
    "id": "anim-preloader",
    "name": "Preloader",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-preloader.tsx",
    "exportName": "Preloader",
    "isDefault": true,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-starter/tw/preloader.tsx"
  },
  {
    "id": "anim-radial-liquid",
    "name": "Radial Liquid",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-radial-liquid.tsx",
    "exportName": "RadialLiquid",
    "isDefault": true,
    "deps": [
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/radial-liquid.tsx"
  },
  {
    "id": "anim-retro-lines",
    "name": "Retro Lines",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-retro-lines.tsx",
    "exportName": "RetroLines",
    "isDefault": true,
    "deps": [
      "@react-three/fiber",
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/retro-lines.tsx"
  },
  {
    "id": "anim-rising-lines",
    "name": "Rising Lines",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-rising-lines.tsx",
    "exportName": "RisingLines",
    "isDefault": true,
    "deps": [
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/rising-lines.tsx"
  },
  {
    "id": "anim-rotating-cards",
    "name": "Rotating Cards",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-rotating-cards.tsx",
    "exportName": "RotatingCards",
    "isDefault": true,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-starter/tw/rotating-cards.tsx"
  },
  {
    "id": "anim-rotating-stars",
    "name": "Rotating Stars",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-rotating-stars.tsx",
    "exportName": "RotatingStars",
    "isDefault": true,
    "deps": [
      "@react-three/fiber",
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/rotating-stars.tsx"
  },
  {
    "id": "anim-rubber-fluid",
    "name": "Rubber Fluid",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-rubber-fluid.tsx",
    "exportName": "RubberFluid",
    "isDefault": true,
    "deps": [
      "@react-three/fiber",
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/rubber-fluid.tsx"
  },
  {
    "id": "anim-shader-card",
    "name": "Shader Card",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-shader-card.tsx",
    "exportName": "ShaderCard",
    "isDefault": true,
    "deps": [
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/shader-card.tsx"
  },
  {
    "id": "anim-shader-reveal",
    "name": "Shader Reveal",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-shader-reveal.tsx",
    "exportName": "ShaderReveal",
    "isDefault": true,
    "deps": [
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/shader-reveal.tsx"
  },
  {
    "id": "anim-shader-waves",
    "name": "Shader Waves",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-shader-waves.tsx",
    "exportName": "ShaderWaves",
    "isDefault": true,
    "deps": [
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/shader-waves.tsx"
  },
  {
    "id": "anim-shadow-bars",
    "name": "Shadow Bars",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-shadow-bars.tsx",
    "exportName": "ShadowBars",
    "isDefault": true,
    "deps": [
      "@react-three/fiber",
      "next-themes",
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/shadow-bars.tsx"
  },
  {
    "id": "anim-silk-waves",
    "name": "Silk Waves",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-silk-waves.tsx",
    "exportName": "SilkWaves",
    "isDefault": true,
    "deps": [
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/silk-waves.tsx"
  },
  {
    "id": "anim-simple-graph",
    "name": "Simple Graph",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-simple-graph.tsx",
    "exportName": "SimpleGraph",
    "isDefault": true,
    "deps": [
      "motion",
      "lucide-react"
    ],
    "heavy": false,
    "source": "reactbits-starter/tw/simple-graph.tsx"
  },
  {
    "id": "anim-simple-swirl",
    "name": "Simple Swirl",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-simple-swirl.tsx",
    "exportName": "SimpleSwirl",
    "isDefault": true,
    "deps": [
      "@react-three/fiber",
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/simple-swirl.tsx"
  },
  {
    "id": "anim-smooth-cursor",
    "name": "Smooth Cursor",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-smooth-cursor.tsx",
    "exportName": "SmoothCursor",
    "isDefault": true,
    "deps": [],
    "heavy": false,
    "source": "reactbits-starter/tw/smooth-cursor.tsx"
  },
  {
    "id": "anim-square-matrix",
    "name": "Square Matrix",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-square-matrix.tsx",
    "exportName": "SquareMatrix",
    "isDefault": true,
    "deps": [
      "@react-three/fiber",
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/square-matrix.tsx"
  },
  {
    "id": "anim-squircle-shift",
    "name": "Squircle Shift",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-squircle-shift.tsx",
    "exportName": "SquircleShift",
    "isDefault": true,
    "deps": [
      "@react-three/fiber",
      "three",
      "next-themes"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/squircle-shift.tsx"
  },
  {
    "id": "anim-staggered-text",
    "name": "Staggered Text",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-staggered-text.tsx",
    "exportName": "StaggeredText",
    "isDefault": true,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-starter/tw/staggered-text.tsx"
  },
  {
    "id": "anim-star-burst",
    "name": "Star Burst",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-star-burst.tsx",
    "exportName": "StarBurst",
    "isDefault": true,
    "deps": [
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/star-burst.tsx"
  },
  {
    "id": "anim-star-swipe",
    "name": "Star Swipe",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-star-swipe.tsx",
    "exportName": "StarSwipe",
    "isDefault": true,
    "deps": [
      "@react-three/fiber",
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/star-swipe.tsx"
  },
  {
    "id": "anim-swirl-blend",
    "name": "Swirl Blend",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-swirl-blend.tsx",
    "exportName": "SwirlBlend",
    "isDefault": true,
    "deps": [
      "@react-three/fiber",
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/swirl-blend.tsx"
  },
  {
    "id": "anim-synaptic-shift",
    "name": "Synaptic Shift",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-synaptic-shift.tsx",
    "exportName": "SynapticShift",
    "isDefault": true,
    "deps": [
      "@react-three/fiber",
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/synaptic-shift.tsx"
  },
  {
    "id": "anim-text-cube",
    "name": "Text Cube",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-text-cube.tsx",
    "exportName": "TextCube",
    "isDefault": true,
    "deps": [],
    "heavy": false,
    "source": "reactbits-starter/tw/text-cube.tsx"
  },
  {
    "id": "anim-text-path",
    "name": "Text Path",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-text-path.tsx",
    "exportName": "TextPath",
    "isDefault": true,
    "deps": [
      "gsap",
      "@gsap/react"
    ],
    "heavy": false,
    "source": "reactbits-starter/tw/text-path.tsx"
  },
  {
    "id": "anim-text-scatter",
    "name": "Text Scatter",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-text-scatter.tsx",
    "exportName": "TextScatter",
    "isDefault": true,
    "deps": [
      "gsap"
    ],
    "heavy": false,
    "source": "reactbits-starter/tw/text-scatter.tsx"
  },
  {
    "id": "anim-twilight-lines",
    "name": "Twilight Lines",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-twilight-lines.tsx",
    "exportName": "TwilightLines",
    "isDefault": true,
    "deps": [
      "@react-three/fiber",
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/twilight-lines.tsx"
  },
  {
    "id": "anim-user-cursor",
    "name": "User Cursor",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-user-cursor.tsx",
    "exportName": "UserCursor",
    "isDefault": true,
    "deps": [
      "motion"
    ],
    "heavy": false,
    "source": "reactbits-starter/tw/user-cursor.tsx"
  },
  {
    "id": "anim-vortex",
    "name": "Vortex",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-vortex.tsx",
    "exportName": "Vortex",
    "isDefault": true,
    "deps": [],
    "heavy": false,
    "source": "reactbits-starter/tw/vortex.tsx"
  },
  {
    "id": "anim-warp-twister",
    "name": "Warp Twister",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-warp-twister.tsx",
    "exportName": "WarpTwister",
    "isDefault": true,
    "deps": [
      "@react-three/fiber",
      "next-themes",
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/warp-twister.tsx"
  },
  {
    "id": "anim-warped-card",
    "name": "Warped Card",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-warped-card.tsx",
    "exportName": "WarpedCard",
    "isDefault": true,
    "deps": [
      "@react-three/fiber",
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/warped-card.tsx"
  },
  {
    "id": "anim-watercolor",
    "name": "Watercolor",
    "group": "animations",
    "category": "animation",
    "categoryLabel": "动画组件",
    "file": "anim-watercolor.tsx",
    "exportName": "Watercolor",
    "isDefault": true,
    "deps": [
      "@react-three/fiber",
      "three"
    ],
    "heavy": true,
    "source": "reactbits-starter/tw/watercolor.tsx"
  }
];
